name: CI

on:
  pull_request:
    branches:
    - main

jobs:
  ci:
    name: CI
    runs-on: ubuntu-22.04
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: CI
      uses: "./.github/template/build"
      with:
        gh-token: ${{ secrets.GITHUB_TOKEN }}
